#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}"
LAUNCHER="${REPO_ROOT}/launch_pccr.sh"

ENV_PATH="${ENV_PATH:-/nexus/posix0/MBR-neuralsystems/alim/envs/hvit}"
DATA_ROOT_DEFAULT="${DATA_ROOT_DEFAULT:-/nexus/posix0/MBR-neuralsystems/alim/regdata/oasis}"
AIM_REPO_DEFAULT="${AIM_REPO_DEFAULT:-${REPO_ROOT}/aim}"
CONFIG_PATH="${CONFIG_PATH:-src/pccr/configs/pairwise_oasis_v4e.yaml}"
INIT_CHECKPOINT_PATH="${INIT_CHECKPOINT_PATH:-${REPO_ROOT}/checkpoints/pccr/pccr_oasis_real_20260329-100814/epoch1365-val1.5977.ckpt}"
RUN_TAG="${RUN_TAG:-$(date +"%Y%m%d-%H%M%S")}"
REAL_EXPERIMENT_NAME="${REAL_EXPERIMENT_NAME:-pccr_oasis_real_v4e_${RUN_TAG}}"

NUM_GPUS_PER_NODE="${NUM_GPUS_PER_NODE:-4}"
BATCH_SIZE_DEFAULT="${BATCH_SIZE_DEFAULT:-1}"
NUM_WORKERS_DEFAULT="${NUM_WORKERS_DEFAULT:-8}"
PRECISION_DEFAULT="${PRECISION_DEFAULT:-bf16-mixed}"
LR_REAL_DEFAULT="${LR_REAL_DEFAULT:-2e-5}"
MAX_EPOCHS_REAL_DEFAULT="${MAX_EPOCHS_REAL_DEFAULT:-200}"
TRAIN_NUM_STEPS_REAL_DEFAULT="${TRAIN_NUM_STEPS_REAL_DEFAULT:-600}"
MAX_VAL_PAIRS_REAL_DEFAULT="${MAX_VAL_PAIRS_REAL_DEFAULT:-20}"
ITER_EVAL_EVERY_N_EPOCHS_DEFAULT="${ITER_EVAL_EVERY_N_EPOCHS_DEFAULT:-25}"
ITER_EVAL_NUM_PAIRS_DEFAULT="${ITER_EVAL_NUM_PAIRS_DEFAULT:-100}"
ITER_VIZ_EVERY_N_EPOCHS_DEFAULT="${ITER_VIZ_EVERY_N_EPOCHS_DEFAULT:-50}"
ITER_VIZ_PAIR_INDEX_DEFAULT="${ITER_VIZ_PAIR_INDEX_DEFAULT:-0}"

export ENV_PATH DATA_ROOT_DEFAULT AIM_REPO_DEFAULT NUM_GPUS_PER_NODE BATCH_SIZE_DEFAULT NUM_WORKERS_DEFAULT PRECISION_DEFAULT
export LR_REAL_DEFAULT MAX_EPOCHS_REAL_DEFAULT TRAIN_NUM_STEPS_REAL_DEFAULT MAX_VAL_PAIRS_REAL_DEFAULT

CMD=(
  "${LAUNCHER}"
  --phase real
  --experiment_name "${REAL_EXPERIMENT_NAME}"
  --checkpoint_path "${INIT_CHECKPOINT_PATH}"
  --config "${CONFIG_PATH}"
  --max_epochs "${MAX_EPOCHS_REAL_DEFAULT}"
  --train_num_steps "${TRAIN_NUM_STEPS_REAL_DEFAULT}"
  --lr "${LR_REAL_DEFAULT}"
  --max_val_pairs "${MAX_VAL_PAIRS_REAL_DEFAULT}"
  --iter_eval_every_n_epochs "${ITER_EVAL_EVERY_N_EPOCHS_DEFAULT}"
  --iter_eval_num_pairs "${ITER_EVAL_NUM_PAIRS_DEFAULT}"
  --iter_eval_skip_hd95
  --iter_viz_every_n_epochs "${ITER_VIZ_EVERY_N_EPOCHS_DEFAULT}"
  --iter_viz_pair_index "${ITER_VIZ_PAIR_INDEX_DEFAULT}"
)

printf '[run_pccr_oasis_v4e.sh] Command:'
printf ' %q' "${CMD[@]}"
printf '\n'

"${CMD[@]}"
