#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${REPO_ROOT:-${SCRIPT_DIR}}"
LAUNCHER="${LAUNCHER:-${REPO_ROOT}/launch_pccr_transmorph_pkl_phase.sh}"

RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
EXPERIMENT_PREFIX="${EXPERIMENT_PREFIX:-pccr_transmorph_pkl_half_v5_${RUN_ID}}"
SYN_EXPERIMENT_NAME="${SYN_EXPERIMENT_NAME:-${EXPERIMENT_PREFIX}_synthetic}"
REAL_EXPERIMENT_NAME="${REAL_EXPERIMENT_NAME:-${EXPERIMENT_PREFIX}_real}"
SYN_CHECKPOINT_PATH="${SYN_CHECKPOINT_PATH:-}"

CONFIG_PATH="${CONFIG_PATH:-${REPO_ROOT}/config/pairwise_oasis_transmorph_pkl_half_v5.yaml}"
JOB_NAME_SYNTH="${JOB_NAME_SYNTH:-pccr_tm_pkl_half_v5_syn}"
JOB_NAME_REAL="${JOB_NAME_REAL:-pccr_tm_pkl_half_v5_real}"

COMMON_POLL_SECONDS="${COMMON_POLL_SECONDS:-60}"
COMMON_HEARTBEAT_POLLS="${COMMON_HEARTBEAT_POLLS:-5}"
COMMON_MAX_TOTAL_RESTARTS="${COMMON_MAX_TOTAL_RESTARTS:-100}"
COMMON_MAX_RESTARTS_WITHOUT_CHECKPOINT="${COMMON_MAX_RESTARTS_WITHOUT_CHECKPOINT:-2}"

SYNTH_MAX_EPOCHS="${SYNTH_MAX_EPOCHS:-50}"
SYNTH_TRAIN_NUM_STEPS="${SYNTH_TRAIN_NUM_STEPS:-200}"
SYNTH_LR="${SYNTH_LR:-1e-4}"

REAL_MAX_EPOCHS="${REAL_MAX_EPOCHS:-200}"
REAL_TRAIN_NUM_STEPS="${REAL_TRAIN_NUM_STEPS:-600}"
REAL_LR="${REAL_LR:-2e-5}"

CHECKPOINT_EVERY_N_TRAIN_STEPS="${CHECKPOINT_EVERY_N_TRAIN_STEPS:-250}"
CHECK_VAL_EVERY_N_EPOCH="${CHECK_VAL_EVERY_N_EPOCH:-10}"
LOG_EVERY_N_STEPS="${LOG_EVERY_N_STEPS:-10}"
MAX_VAL_PAIRS="${MAX_VAL_PAIRS:-19}"
PYTHONDONTWRITEBYTECODE="${PYTHONDONTWRITEBYTECODE:-1}"
PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
FINAL_COST_VOLUME_MODE="${FINAL_COST_VOLUME_MODE:-off}"
FINAL_COST_VOLUME_RADIUS="${FINAL_COST_VOLUME_RADIUS:-0}"
FINAL_COST_VOLUME_CHUNK_SIZE="${FINAL_COST_VOLUME_CHUNK_SIZE:-16}"

FULL_LOG_DIR="${REPO_ROOT}/logs/pccr/${EXPERIMENT_PREFIX}_launcher"
FULL_LOG_FILE="${FULL_LOG_DIR}/launch_full.log"
mkdir -p "${FULL_LOG_DIR}"
exec > >(tee -a "${FULL_LOG_FILE}") 2>&1

echo "=========================================="
echo "PCCR TransMorph PKL Half V5-Style Full Launcher"
echo "Synthetic experiment: ${SYN_EXPERIMENT_NAME}"
echo "Real experiment: ${REAL_EXPERIMENT_NAME}"
echo "Config: ${CONFIG_PATH}"
echo "Launcher: ${LAUNCHER}"
echo "Timestamp: $(date)"
echo "=========================================="

export CONFIG_PATH
export COMMON_POLL_SECONDS
export COMMON_HEARTBEAT_POLLS
export COMMON_MAX_TOTAL_RESTARTS
export COMMON_MAX_RESTARTS_WITHOUT_CHECKPOINT
export CHECKPOINT_EVERY_N_TRAIN_STEPS
export CHECK_VAL_EVERY_N_EPOCH
export LOG_EVERY_N_STEPS
export MAX_VAL_PAIRS
export PYTHONDONTWRITEBYTECODE
export PYTORCH_CUDA_ALLOC_CONF
export FINAL_COST_VOLUME_MODE
export FINAL_COST_VOLUME_RADIUS
export FINAL_COST_VOLUME_CHUNK_SIZE

SYNTH_CMD=(
  "${LAUNCHER}"
  --phase synthetic
  --experiment_name "${SYN_EXPERIMENT_NAME}"
)
if [[ -n "${SYN_CHECKPOINT_PATH}" ]]; then
  SYNTH_CMD+=(--checkpoint_path "${SYN_CHECKPOINT_PATH}")
fi

POLL_SECONDS="${COMMON_POLL_SECONDS}" \
HEARTBEAT_POLLS="${COMMON_HEARTBEAT_POLLS}" \
MAX_TOTAL_RESTARTS="${COMMON_MAX_TOTAL_RESTARTS}" \
MAX_RESTARTS_WITHOUT_CHECKPOINT="${COMMON_MAX_RESTARTS_WITHOUT_CHECKPOINT}" \
JOB_NAME="${JOB_NAME_SYNTH}" \
MAX_EPOCHS="${SYNTH_MAX_EPOCHS}" \
TRAIN_NUM_STEPS="${SYNTH_TRAIN_NUM_STEPS}" \
LR="${SYNTH_LR}" \
"${SYNTH_CMD[@]}"

FINAL_SYNTH_CKPT="/u/almik/others/hvit/symlinks/experiments_pccr/checkpoints/pccr/${SYN_EXPERIMENT_NAME}/last.ckpt"
if [[ ! -s "${FINAL_SYNTH_CKPT}" ]]; then
  echo "[half_v5_full] Synthetic completed, but checkpoint was not found: ${FINAL_SYNTH_CKPT}" >&2
  exit 1
fi

echo "[half_v5_full] Synthetic completed."
echo "[half_v5_full] Real will initialize from: ${FINAL_SYNTH_CKPT}"

POLL_SECONDS="${COMMON_POLL_SECONDS}" \
HEARTBEAT_POLLS="${COMMON_HEARTBEAT_POLLS}" \
MAX_TOTAL_RESTARTS="${COMMON_MAX_TOTAL_RESTARTS}" \
MAX_RESTARTS_WITHOUT_CHECKPOINT="${COMMON_MAX_RESTARTS_WITHOUT_CHECKPOINT}" \
JOB_NAME="${JOB_NAME_REAL}" \
MAX_EPOCHS="${REAL_MAX_EPOCHS}" \
TRAIN_NUM_STEPS="${REAL_TRAIN_NUM_STEPS}" \
LR="${REAL_LR}" \
"${LAUNCHER}" \
  --phase real \
  --experiment_name "${REAL_EXPERIMENT_NAME}" \
  --checkpoint_path "${FINAL_SYNTH_CKPT}"

echo "[half_v5_full] Full synthetic -> real pipeline completed."
